## i2c for DFROBOT GRAVITY SCD41, CO2 sensor. I2C must be enabled.
sensor:
  ## extra SCD41 sensor on the house suction side as it is not present in the Brink Flair.
  - platform: scd4x
    co2:
      name: ${brink_co2_from_inside}
      id: brink_co2_from_inside
      on_value:
        then:
        - if:
            condition:
              lambda: 'return x < 1000;'
            then:
            else:
            - if:
                condition:
                  lambda: 'return x > 1500;'
                then:
                else:
        
    humidity:
      name: ${brink_humidity_from_inside}
      id: brink_humidity_from_inside
      on_value:
        then:
        - if:
            condition:
              lambda: 'return x < 30;'
            then:
            else:
            - if:
                condition:
                  lambda: 'return x > 60;'
                then:
                else:

    temperature:
      name: ${brink_temp_from_inside}
      id: brink_temp_from_inside

    temperature_offset: "2.0°C"

## Performance now can be calculated with the extra temperature sensor.     
  - id: brink_performance
    name: ${brink_performance}
    platform: template
    unit_of_measurement: "%"
    update_interval: 30s
    lambda: 'return ((id(brink_temp_to_inside).state - id(brink_temp_from_outside).state)/(id(brink_temp_from_inside).state - id(brink_temp_from_outside).state)*100);'
   # (temp_to_inside - temp_from_outside) / (temp_from_inside - temp_from_outside)