number:
# Maximum value for Flair 300 is 300m3/h
  - id: brink_modbus_flow_rate
    name: "${name} ${brink_modbus_flow_rate}"
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 8002
    value_type: S_WORD
    min_value: 0
    max_value: 300
    mode: slider

  - id: brink_flow_0
    name: "${name} Flow 0"
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 6000
    unit_of_measurement: "m3/h"
    value_type: S_WORD
    min_value: 0
    max_value: 300
    mode: slider
    icon: mdi:fan-auto

  - id: brink_flow_1
    name: "${name} Flow 1"
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 6001
    unit_of_measurement: "m3/h"
    value_type: S_WORD
    min_value: 50
    max_value: 300
    mode: slider
    icon: mdi:fan-speed-1

  - id: brink_flow_2
    name: "${name} Flow 2"
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 6002
    unit_of_measurement: "m3/h"
    value_type: S_WORD
    min_value: 50
    max_value: 300
    mode: slider
    icon: mdi:fan-speed-2

  - id: brink_flow_3
    name: "${name} Flow 3"
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 6003
    unit_of_measurement: "m3/h"
    value_type: S_WORD
    min_value: 50
    max_value: 300
    mode: slider
    icon: mdi:fan-speed-3