# Based on a Flair 400, to changes max values for Flair 300 change all max_value in lines 725 - 774 to 325
substitutions:
  name: brink
  friendly_name: Brink
  device_description: "Esphome component for Brink Flair with modbus"
  timezone: "Europe/Amsterdam"

# In order to use other language or a different ESP chip, fix include file name below:
# Currently supported languages are en, nl. 
# ESP32 is a mh-et-live or wemos d32 mini, esp8266 is a wemos d1 mini, esp32s3 is a lilygo ESP32S3-T7
# Be carefull not to upload the wrong code to the wrong chip. This could brick your ESP chip.

packages:
  remote_package:
    url: https://github.com/fonske/Brink-flair-modbus
    ref: main
    files: 
      - esphome/labels/.brink-labels-en.yaml
      # - esphome/labels/.brink-labels-nl.yaml
      - esphome/.brink.base.yaml
      # - esphome/sensors/sensor-scd41-i2c-dfrobot.yaml
      # - esphome/sensors/sensor-scd41-i2c-m5stack.yaml
      # - esphome/sensors/sensor-enviii-i2c-m5stack.yaml
      # - esphome/sensors/sensor-dht22.yaml

# for developing/testing, uncomment local includes and comment out remote_package part.
# packages:
#   substitutions: !include labels/.brink-labels-en.yaml
#   device_base1: !include .brink.base.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Put your API key here if you have one
# api:
#   encryption:
#     key: !secret brink_api_key

esp8266:
  board: nodemcuv2

uart:
  tx_pin: D1
  rx_pin: D2
  id: mod_bus
  baud_rate: 19200
  stop_bits: 1
  parity: even

# Enable/Disable logging - ESP8266 is low on memory, so logger is disabled by default
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    dht.sensor: WARN
    switch: WARN
    button: WARN
    number: WARN
  # baud_rate: 0  # <--- uncomment if you have issues with ESP8266 (wifi upload fails, etc.)

# captative portal and webserver is disabled for ESP8266 due low RAM.
# if enabled, it leads to unstable operation, Wifi disconnects, etc.
