### ESP32 used is a MH-ET-LIVE, also known as Wemos D32 Mini 
### The modbus TTL to RS485 interface used is a XY-017  (RS3485). No flow control needed and 3.3V powersupply

# Based on a Flair 400, to changes max values for Flair 300 change all max_value in lines 725 - 774 to 325
substitutions:
  name: brink
  friendly_name: Brink
  device_description: "Esphome component for Brink Flair with modbus"
  timezone: "Europe/Amsterdam"

# In order to use other language or a different ESP chip, fix include file name below:
# Currently supported languages are en, nl. 
packages:
  remote_package:
    url: https://github.com/fonske/Brink-flair-modbus
    ref: main
    files: 
      - esphome/labels/.brink-labels-en.yaml
#       # - esphome/labels/.brink-labels-nl.yaml
      - esphome/.brink.base.yaml
#       # - esphome/sensors/sensor-scd41-i2c-dfrobot.yaml
#       # - esphome/sensors/sensor-scd41-i2c-m5stack.yaml
#       # - esphome/sensors/sensor-enviii-i2c-m5stack.yaml
#       # - esphome/sensors/sensor-dht22.yaml

# for developing/testing, uncomment local includes and comment out remote_package part.
# packages:
#   substitutions: !include labels/.brink-labels-en.yaml
#   device_base1: !include .brink.base.yaml

# Put your API key here if you have one
# api:
#   encryption:
#     key: !secret brink_api_key

esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

# uart for modbus rtu
uart:
  id: mod_bus
  baud_rate: 19200
  stop_bits: 1
  tx_pin: 23
  rx_pin: 19
  parity: even  

# i2c for extra sensor
i2c:  
  sda: 21
  scl: 22
  scan: true
  id: bus_a

# Enable/Disable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    dht.sensor: WARN
    switch: WARN
    button: WARN
    number: WARN
  # baud_rate: 0  # <--- super important! for ESP8266

wifi:
  ap:
    ssid: "${name} hotspot"
    password: "configesp"
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Enable Web server.
web_server:
  port: 80
