name: Build ESPHome firmware

# Controls when the action will run. Triggers the workflow on push
on: 
  push:
  pull_request:
  release:
        
jobs:
  device_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
        devices: [brink-esp32.yaml, brink-esp8266.yaml]
    runs-on: ${{ matrix.os }}
    name: "Build"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Extract branch name
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch        
      - name: "Test on local include files"
        run: |
          # awk  '/^[ -]+esphome\/(boards|sensors|.brink)/ {sub("esphome", "device_base"++count":& ")} 1' esphome/brink.yaml 
          sed -i '/remote_package:/,+10d' esphome/${{ matrix.devices }}
          sed -i '/^packages:/a\ \ substitutions: !include labels/.brink-labels-en.yaml\n\ \ device_base: !include .brink.base.yaml' esphome/${{ matrix.devices }}
      #     awk  '/^[ -]+esphome\/(boards|sensors|.brink)/ {sub("esphome", "device_base"++count":& ")} 1' esphome/brink.yaml 
      - name: "Build"
        uses: esphome/build-action@v1.8.0
        id: esphome-build
        with:
          yaml_file: esphome/${{ matrix.devices }}
